(ns nubank-exercise.util.message)

(def _01 "Error: you informed a position outside the grid or is giving a robot instruction to a non-robot")
(def _02 "Error: you informed a position outside the grid or the position is already occupied")
(def _03 "Error: the robot cannot move to this direction")
(def _04 "Error: no valid direction informed. Accepted options -> [backward|forward]")
(def _05 "Error: you informed a position outside the grid or the position is already occupied or an invalid direction value")
(def _06 "Info: no dinosaurs were destroyed")
(def _07 "Error: no valid direction informed. Accepted options -> [left|right]")
(def _08 "Error: caught an exception, please report")
(def _09 "Info: grid created")
(def _10 "Error: grid not initiated")
(def _11 "Info: grid updated")
(def _12 "Error: please, columns and rows must be formed by positive integers only")
(def _13 "Error: please, columns, rows and direction must be formed by positive integers only")